version: "3.9"

services:
  server:
    container_name: schools_api
    build: .
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${PORT}:${PORT}

  mysql:
    container_name: mysql_local
    image: mysql:8.0
    environment:
      - MYSQL_HOST=${DATABASE_HOST}
      - MYSQL_TCP_PORT=${DATABASE_PORT}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./docker-mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - '3306:${DATABASE_PORT}'
    restart: always

volumes:
  mysql:
